#!/bin/sh

set -e

if [ -z "$1" ]; then
  echo "module name required"
  exit 1
fi

module="$1"
gem=$(basename `pwd`)

echo $gem setup

sed -i '' "s/MY_NEW_GEM/$module/g" *.gemspec
grep -lr module lib | xargs sed -i '' "s/module MY_NEW_GEM/module $module/g"

UPSTREAM=`git rev-parse --abbrev-ref --symbolic-full-name @{u} | cut -d/ -f1`
URL=`git remote get-url --push $UPSTREAM`
# remove .git suffix
URL=${URL%%.git}
repo="${URL##*/}"
sed -i '' "s/MY_NEW_GEM_rb/$repo/g" README.md # repo

sed -i '' "1s/MY_NEW_GEM/$module/" README.md # first line

# remaining references
grep -lr MY_NEW_GEM *.md lib | xargs sed -i '' "s/MY_NEW_GEM/$gem/g"

mv MY_NEW_GEM.gemspec $gem.gemspec
mv lib/MY_NEW_GEM.rb lib/$gem.rb
mv lib/MY_NEW_GEM lib/$gem

# purge this setup script
rm $0

# commit
git add .
git commit -m "$gem setup"
git push
